import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, ChevronDown, Crosshair, Grid3X3, Menu, RotateCcw, Settings2, ShieldCheck, TrendingDown, TrendingUp, ZoomIn, ZoomOut } from "lucide-react";
import { SiteLayout } from "@/components/site-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/trading-lab")({
  head: () => ({ meta: [{ title: "Trading Lab — Trading Academy CZ" }, { name: "description", content: "MT5-style demo terminál pro bezpečný nácvik tradingu." }] }),
  component: TradingLab,
});

type Candle={o:number;h:number;l:number;c:number};
type Position={id:number;side:"BUY"|"SELL";volume:number;entry:number;sl:number;tp:number};
type Asset={symbol:string;digits:number;seed:number;point:number;name:string};

const assets:Asset[]=[
 {symbol:"EURUSD",name:"Euro vs US Dollar",digits:5,seed:1.16542,point:.00001},
 {symbol:"GBPUSD",name:"British Pound vs US Dollar",digits:5,seed:1.34618,point:.00001},
 {symbol:"USDJPY",name:"US Dollar vs Japanese Yen",digits:3,seed:147.284,point:.001},
 {symbol:"XAUUSD",name:"Gold vs US Dollar",digits:2,seed:3645.20,point:.01},
 {symbol:"BTCUSD",name:"Bitcoin vs US Dollar",digits:2,seed:112450.32,point:.01},
 {symbol:"US500",name:"US 500",digits:2,seed:6512.4,point:.01},
];
const tfs=["M1","M2","M3","M4","M5","M6","M10","M12","M15","M20","M30","H1","H2","H3","H4","H6","H8","H12","D1","W1","MN"];
function candles(seed:number){let p=seed;const a:Candle[]=[];for(let i=0;i<160;i++){const wave=(Math.sin(i*.34)*.7+Math.cos(i*.13)*.32+Math.sin(i*1.51)*.12)*seed*.00105;const body=seed*(.00025+Math.abs(Math.sin(i*1.2))*.00016);const o=p,c=p+wave,h=Math.max(o,c)+body,l=Math.min(o,c)-body*.8;a.push({o,h,l,c});p=c;}return a}
function f(v:number,d:number){return v.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}
function pnlText(v:number){return `${v>=0?"+":"-"}$${Math.abs(v).toFixed(2)}`}

function TradingLab(){
 const [ai,setAi]=useState(0); const asset=assets[ai]; const [tf,setTf]=useState("M15"); const [data]=useState(()=>candles(asset.seed));
 const [visible,setVisible]=useState(60); const [balance,setBalance]=useState(10000); const [volume,setVolume]=useState(.10); const [slPts,setSlPts]=useState(250); const [tpPts,setTpPts]=useState(500); const [positions,setPositions]=useState<Position[]>([]); const [bottom,setBottom]=useState("Trade"); const [left,setLeft]=useState("Market Watch"); const [grid,setGrid]=useState(true); const [cross,setCross]=useState(false);
 const shown=data.slice(0,visible), current=shown.at(-1)?.c??asset.seed; const prev=shown.at(-2)?.c??current; const delta=current-prev;
 const calc=(p:Position)=>{const d=p.side==="BUY"?current-p.entry:p.entry-current;const pv=["XAUUSD","BTCUSD","US500"].includes(asset.symbol)?.1:1;return d/asset.point*p.volume*.01*pv};
 const floatPnl=useMemo(()=>positions.reduce((s,p)=>s+calc(p),0),[positions,current,asset]); const equity=balance+floatPnl; const margin=positions.reduce((s,p)=>s+p.volume*100,0);
 const hi=Math.max(...shown.map(c=>c.h)),lo=Math.min(...shown.map(c=>c.l)),range=Math.max(hi-lo,asset.point),W=1100,H=500,L=20,R=88,T=18,B=30,step=(W-L-R)/shown.length,y=(v:number)=>T+(1-(v-lo)/range)*(H-T-B);
 const open=(side:"BUY"|"SELL")=>{const sl=side==="BUY"?current-slPts*asset.point:current+slPts*asset.point;const tp=side==="BUY"?current+tpPts*asset.point:current-tpPts*asset.point;setPositions(p=>[...p,{id:Date.now(),side,volume,entry:current,sl,tp}]);};
 const close=(id:number)=>{const p=positions.find(x=>x.id===id);if(!p)return;setBalance(b=>b+calc(p));setPositions(xs=>xs.filter(x=>x.id!==id));};
 const select=(i:number)=>{setAi(i);setVisible(60);setBalance(10000);setPositions([]);};
 return <SiteLayout><div className="bg-[#101216] text-[#d9dce4]"><div className="mx-auto max-w-[1600px] p-2 sm:p-3"><div className="overflow-hidden border border-white/10 bg-[#17191f] shadow-2xl">
  <div className="flex h-9 items-center justify-between border-b border-white/10 bg-[#20232a] px-3 text-xs"><div className="flex items-center gap-2"><BarChart3 className="size-4 text-yellow-300"/><b>Trading Academy — Demo Terminal</b><Badge className="bg-emerald-500/15 text-emerald-300">DEMO</Badge></div><span className="text-emerald-300">● Connected</span></div>
  <div className="flex flex-wrap items-center gap-1 border-b border-white/10 bg-[#1c1f25] px-2 py-1 text-[11px]">{["File","View","Insert","Charts","Tools","Window","Help"].map(x=><button key={x} className="rounded px-2 py-1 hover:bg-white/10">{x}</button>)}<span className="mx-1 h-4 w-px bg-white/10"/>{["New Order","Crosshair","Indicators","AutoTrading"].map(x=><button key={x} className="rounded px-2 py-1 hover:bg-white/10">{x}</button>)}<button className="ml-auto rounded p-1.5 hover:bg-white/10"><Settings2 className="size-3.5"/></button></div>
  <div className="grid grid-cols-[230px_1fr]">
   <aside className="hidden border-r border-white/10 bg-[#17191e] md:block"><div className="grid grid-cols-2 border-b border-white/10 bg-[#20232a] text-[11px]">{["Market Watch","Navigator"].map(x=><button key={x} onClick={()=>setLeft(x)} className={`px-3 py-2 ${left===x?"bg-[#292d36] text-white":"text-slate-500"}`}>{x}</button>)}</div>{left==="Market Watch"?<><div className="flex justify-between px-3 py-2 text-[10px] uppercase tracking-wider text-slate-500"><span>Symbols</span><span>Bid / Ask</span></div>{assets.map((a,i)=>{const p=candles(a.seed)[59].c;const ask=p+a.point*4;return <button key={a.symbol} onClick={()=>select(i)} className={`grid w-full grid-cols-[1fr_76px_76px] px-3 py-2 text-left text-xs hover:bg-white/5 ${i===ai?"bg-[#292d36]":""}`}><b>{a.symbol}</b><span>{f(p,a.digits)}</span><span>{f(ask,a.digits)}</span></button>})}</>:<div className="p-3 text-xs text-slate-400 space-y-2">{["Accounts","Indicators","Expert Advisors","Scripts"].map(x=><div key={x}>▸ {x}</div>)}</div>}</aside>
   <main className="min-w-0">
    <div className="flex flex-wrap items-center gap-1 border-b border-white/10 bg-[#1a1d23] px-2 py-1"> <button className="flex items-center gap-2 rounded bg-[#2a2e37] px-3 py-1.5 text-xs font-semibold">{asset.symbol}<ChevronDown className="size-3"/></button>{tfs.map(x=><button key={x} onClick={()=>setTf(x)} className={`rounded px-2 py-1.5 text-[10px] ${tf===x?"bg-yellow-300 text-black font-semibold":"text-slate-500 hover:bg-white/10"}`}>{x}</button>)}<div className="ml-auto flex gap-1"><button onClick={()=>setGrid(v=>!v)} className="rounded p-1.5 hover:bg-white/10"><Grid3X3 className="size-3.5"/></button><button onClick={()=>setCross(v=>!v)} className="rounded p-1.5 hover:bg-white/10"><Crosshair className="size-3.5"/></button><button className="rounded p-1.5 hover:bg-white/10"><ZoomOut className="size-3.5"/></button><button className="rounded p-1.5 hover:bg-white/10"><ZoomIn className="size-3.5"/></button></div></div>
    <div className="relative overflow-hidden bg-[#0e1015]"><div className="absolute left-3 top-2 z-10 text-[10px] text-slate-500">{asset.symbol},{tf}  ·  {asset.name}</div><svg viewBox={`0 0 ${W} ${H}`} className="h-[500px] w-full">{grid&&[0,.2,.4,.6,.8,1].map(t=><line key={t} x1={L} x2={W-R} y1={T+t*(H-T-B)} y2={T+t*(H-T-B)} stroke="currentColor" opacity=".09"/>)}{shown.map((c,i)=>{const x=L+i*step+step/2,up=c.c>=c.o,top=Math.min(y(c.o),y(c.c)),body=Math.max(2,Math.abs(y(c.c)-y(c.o)));return <g key={i} className={up?"text-emerald-400":"text-red-400"}><line x1={x} x2={x} y1={y(c.h)} y2={y(c.l)} stroke="currentColor"/><rect x={x-step*.3} y={top} width={Math.max(2,step*.6)} height={body} fill="currentColor"/></g>})}<line x1={L} x2={W-R} y1={y(current)} y2={y(current)} stroke="#eab308" strokeDasharray="4 3"/>{[0,.25,.5,.75,1].map(t=><text key={t} x={W-R+8} y={T+t*(H-T-B)+4} fontSize="10" fill="#6f7582">{f(hi-t*range,asset.digits)}</text>)}{cross&&<><line x1={L+(W-L-R)/2} x2={L+(W-L-R)/2} y1={T} y2={H-B} stroke="#fff" opacity=".25"/><line x1={L} x2={W-R} y1={H/2} y2={H/2} stroke="#fff" opacity=".25"/></>}</svg></div>
    <div className="grid grid-cols-2 border-y border-white/10 bg-[#171a20] sm:grid-cols-6">{[["Balance",`$${balance.toFixed(2)}`],["Equity",`$${equity.toFixed(2)}`],["Margin",`$${margin.toFixed(2)}`],["Free Margin",`$${Math.max(0,equity-margin).toFixed(2)}`],["P/L",pnlText(floatPnl)],["Positions",String(positions.length)]].map(([k,v])=><div key={k} className="border-r border-white/5 px-3 py-2"><div className="text-[9px] uppercase tracking-widest text-slate-500">{k}</div><div className={`mt-1 text-xs font-semibold ${k==="P/L"?(floatPnl>=0?"text-emerald-300":"text-red-300"):"text-slate-200"}`}>{v}</div></div>)}</div>
    <div className="grid gap-2 border-b border-white/10 bg-[#1b1e24] p-2 md:grid-cols-[1fr_340px]"><div className="grid grid-cols-2 gap-2"><Button onClick={()=>open("SELL")} className="h-11 bg-red-500/15 text-red-300 hover:bg-red-500/25"><TrendingDown className="size-4"/> SELL <span className="ml-auto text-[10px]">{f(current,asset.digits)}</span></Button><Button onClick={()=>open("BUY")} className="h-11 bg-emerald-500/15 text-emerald-300 hover:bg-emerald-500/25"><TrendingUp className="size-4"/> BUY <span className="ml-auto text-[10px]">{f(current,asset.digits)}</span></Button></div><div className="grid grid-cols-3 gap-2"><label className="text-[10px] text-slate-500">Volume<Input type="number" step="0.01" min="0.01" value={volume} onChange={e=>setVolume(Math.max(.01,Number(e.target.value)||.01))} className="mt-1 h-8 bg-black/20 text-xs"/></label><label className="text-[10px] text-slate-500">SL points<Input type="number" step="10" min="0" value={slPts} onChange={e=>setSlPts(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-8 bg-black/20 text-xs"/></label><label className="text-[10px] text-slate-500">TP points<Input type="number" step="10" min="0" value={tpPts} onChange={e=>setTpPts(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-8 bg-black/20 text-xs"/></label></div></div>
    <div className="bg-[#15171c]"><div className="flex overflow-x-auto border-b border-white/10">{["Trade","Exposure","History","News","Mailbox","Alerts","Experts","Journal"].map(x=><button key={x} onClick={()=>setBottom(x)} className={`px-4 py-2 text-[11px] ${bottom===x?"border-b-2 border-yellow-300 bg-[#252832] text-white":"text-slate-500"}`}>{x}</button>)}</div>{bottom==="Trade"?<div className="max-h-56 overflow-auto"><table className="w-full min-w-[820px] text-[11px]"><thead className="bg-[#1c1f26] text-left text-slate-500"><tr><th className="px-3 py-2">Symbol</th><th>Type</th><th>Volume</th><th>Price</th><th>S/L</th><th>T/P</th><th>Profit</th><th/></tr></thead><tbody>{positions.length===0?<tr><td colSpan={8} className="px-3 py-5 text-slate-600">No open positions</td></tr>:positions.map(p=><tr key={p.id} className="border-t border-white/5"><td className="px-3 py-2 font-semibold">{asset.symbol}</td><td className={p.side==="BUY"?"text-emerald-300":"text-red-300"}>{p.side}</td><td>{p.volume.toFixed(2)}</td><td>{f(p.entry,asset.digits)}</td><td>{f(p.sl,asset.digits)}</td><td>{f(p.tp,asset.digits)}</td><td className={calc(p)>=0?"text-emerald-300":"text-red-300"}>{pnlText(calc(p))}</td><td><Button size="sm" variant="ghost" onClick={()=>close(p.id)} className="h-6 text-[10px]">Close</Button></td></tr>)}</tbody></table></div>:<div className="p-4 text-xs text-slate-500">{bottom} panel — training terminal data.</div>}</div>
    <div className="flex items-center justify-between border-t border-white/10 bg-[#1b1d23] px-3 py-2 text-[10px] text-slate-500"><span>{delta>=0?"Price up":"Price down"} · Spread 4 pts · Demo data</span><Button size="sm" variant="ghost" onClick={()=>{setPositions([]);setBalance(10000);setVisible(60)}} className="h-7 text-[10px]"><RotateCcw className="size-3"/> Reset</Button></div>
   </main>
  </div>
 </div><div className="mt-3 rounded border border-yellow-500/20 bg-yellow-500/5 px-3 py-2 text-[11px] text-slate-400"><ShieldCheck className="mr-2 inline size-3.5 text-yellow-300"/>Demo simulátor: žádný skutečný broker ani reálné peníze.</div></div></div></SiteLayout>;
}
