import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization, apikey","Access-Control-Allow-Methods":"POST, OPTIONS"};
type Feed={q:string;cat:string;weight:number};
type Candidate={cat:string;score:number;date:Date;key:string;source:string;title:string;summary:string;url:string};
const FEEDS:Feed[]=[
{cat:"ipo",weight:14,q:'(IPO OR "initial public offering" OR "IPO filing" OR "go public" OR "stock listing" OR "public debut") (stocks OR shares OR markets)'},
{cat:"makro",weight:11,q:'("Federal Reserve" OR Fed OR ECB OR "Bank of England" OR BOE OR BOJ OR inflation OR CPI OR PCE OR payrolls OR "jobs report" OR "interest rates") (markets OR economy OR bonds)'},
{cat:"ropa",weight:10,q:'(Brent OR WTI OR "crude oil" OR OPEC OR LNG OR "natural gas") (price OR prices OR supply OR production OR market)'},
{cat:"geopolitika",weight:10,q:'(Hormuz OR Iran OR Israel OR "Middle East" OR sanctions OR war OR attack OR shipping) (oil OR markets OR stocks OR energy)'},
{cat:"akcie",weight:9,q:'(Nvidia OR Apple OR Microsoft OR Amazon OR Meta OR Tesla OR Alphabet OR AMD OR earnings OR guidance OR revenue OR profit OR merger OR acquisition) (stocks OR shares)'},
{cat:"komodity",weight:8,q:'(gold OR silver OR copper OR platinum OR palladium OR commodities) (price OR prices OR market)'},
{cat:"forex",weight:8,q:'(dollar OR euro OR yen OR sterling OR USD OR EUR OR JPY OR GBP OR forex OR FX OR "exchange rate" OR currency) (market OR markets OR central bank)'},
{cat:"krypto",weight:7,q:'(bitcoin OR ethereum OR crypto OR cryptocurrency OR stablecoin OR "spot ETF") (market OR markets OR regulation OR flows)'}];
const PRIMARY_SOURCES=["ft.com","bloomberg.com","reuters.com","investing.com","wsj.com"];
const TRUSTED:Record<string,number>={"ft.com":58,"bloomberg.com":58,"reuters.com":56,"investing.com":52,"wsj.com":51,"cnbc.com":49,"marketwatch.com":47,"finance.yahoo.com":45,"nasdaq.com":44,"apnews.com":43,"coindesk.com":45,"cointelegraph.com":38,"sec.gov":52,"nyse.com":50,"londonstockexchange.com":50,"euronext.com":50};
const NAMES:Record<string,string>={"ft.com":"Financial Times","bloomberg.com":"Bloomberg","reuters.com":"Reuters","investing.com":"Investing.com","wsj.com":"The Wall Street Journal","cnbc.com":"CNBC","marketwatch.com":"MarketWatch","finance.yahoo.com":"Yahoo Finance","nasdaq.com":"Nasdaq","apnews.com":"Associated Press","coindesk.com":"CoinDesk","cointelegraph.com":"Cointelegraph","sec.gov":"SEC","nyse.com":"NYSE","londonstockexchange.com":"London Stock Exchange","euronext.com":"Euronext"};
const WHY:Record<string,string>={
ipo:"IPO mění očekávání valuace a kapitálových toků v sektoru. Cena emise, poptávka, valuace a první obchodování mohou ovlivnit i srovnatelné veřejně obchodované firmy.",
makro:"Makrodata a centrální banky mění očekávání sazeb. Přes výnosy dluhopisů se dopad přelévá do diskontních sazeb, valuací akcií, měn a komodit.",
ropa:"Ropa ovlivňuje náklady dopravy a průmyslu i inflaci. Změna ceny proto může změnit očekávání sazeb, marže firem a ziskovost producentů i dovozců.",
geopolitika:"Geopolitika mění rizikovou prémii a může narušit dodávky nebo dopravu. Dopad se může přelít do ropy, inflace, sazeb, měn a akciových indexů.",
akcie:"Výsledky, výhled nebo zásadní firemní rozhodnutí mění očekávání budoucích zisků. Přes EPS a valuaci se dopad šíří na akcii, sektor i indexy.",
komodity:"Komodity reagují na sazby, dolar, globální růst a nabídku s poptávkou. Změna proto ovlivňuje inflační očekávání, náklady výrobců a rizikový sentiment.",
forex:"Forex reaguje hlavně na rozdíl sazeb a očekávání centrálních bank. Přes výnosy dluhopisů se změna rychle propisuje do kurzů měn a dovozní inflace.",
krypto:"Krypto je citlivé na likviditu, ETF toky, regulaci a rizikový apetit. Silná zpráva proto může změnit očekávaný příliv kapitálu a volatilitu trhu."};
const BAD=/\b(technical analysis|chart analysis|price prediction|price target|opinion|podcast|stock picks|best stocks to buy|top stocks to buy|live blog|weekly outlook|daily forecast|what to buy|prediction market|horoscope)\b/i;
const ENTITIES:Record<string,string>={"&amp;":"&","&apos;":"'","&#39;":"'","&quot;":"\"","&#34;":"\"","&lt;":"<","&gt;":">","&nbsp;":" "};
function clean(v:string){let s=String(v||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ");for(let i=0;i<2;i++)s=s.replace(/&(?:amp|apos|#39|quot|#34|lt|gt|nbsp);/gi,m=>ENTITIES[m.toLowerCase()]??m);return s.replace(/[\u0000-\u001F]/g," ").replace(/\s+/g," ").trim()}
function title(v:string){return clean(v).replace(/\s+([,:;.!?])/g,"$1").replace(/([,:;.!?])(?=[A-Za-zÀ-ž])/g,"$1 ").trim()}
function host(url:string){try{return new URL(url).hostname.toLowerCase().replace(/^www\./,"")}catch{return ""}}
function norm(t:string){return title(t).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\b(the|a|an|and|or|to|for|of|in|on|as|at|after|before|with|from|says|said|markets|market|stocks|stock|shares|share|live|update|news)\b/g," ").replace(/\s+/g," ").trim().slice(0,190)}
function latin(t:string){let a=0,n=0;for(const ch of t){if(/[A-Za-zÀ-ž]/.test(ch))a++;if(/\S/.test(ch))n++;}return n===0||a/n>.72}
function dateOf(v?:string){const s=String(v||"");const m=s.match(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/);const d=m?new Date(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`):new Date(s);return Number.isNaN(d.getTime())?new Date():d}
function api(q:string){return `https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(q)}&mode=artlist&maxrecords=250&timespan=24h&sort=datedesc&format=json`}
async function get(q:string){try{const r=await fetch(api(q),{headers:{"User-Agent":"TradingAcademyCZ/23.0"}});if(!r.ok)return[];const j=await r.json();return Array.isArray(j.articles)?j.articles:[]}catch{return[]}}
function classify(t:string){const x=title(t).toLowerCase();if(/\b(ipo|initial public offering|ipo filing|go public|stock listing|public debut|shares offered|prospectus)\b/.test(x))return"ipo";if(/\b(fed|federal reserve|ecb|bank of england|boe|bank of japan|boj|inflation|cpi|pce|payrolls|jobs report|interest rates?|rate hike|rate cut|treasury yields?|bond yields?)\b/.test(x))return"makro";if(/\b(hormuz|iran|israel|middle east|sanctions|war|missile|attack|shipping blockade|ceasefire)\b/.test(x))return"geopolitika";if(/\b(brent|wti|crude oil|oil prices?|opec|lng|natural gas|gasoline|diesel)\b/.test(x))return"ropa";if(/\b(gold|silver|copper|platinum|palladium|commodit(?:y|ies))\b/.test(x))return"komodity";if(/\b(bitcoin|ethereum|crypto|cryptocurrency|stablecoin|spot etf)\b/.test(x))return"krypto";if(/\b(usd|eur|jpy|gbp|dollar|euro|yen|sterling|forex|fx|exchange rate|currency intervention)\b/.test(x))return"forex";if(/\b(nvidia|apple|microsoft|amazon|meta|tesla|alphabet|amd|arm|earnings|guidance|revenue|profit|merger|acquisition|shares? (surge|fall|rise|drop))\b/.test(x))return"akcie";return"jine"}
function score(t:string,cat:string,w:number,source:string,d:Date){const x=t.toLowerCase();let n=w*10+Math.max(0,34-Math.max(0,(Date.now()-d.getTime())/3600000)*2.2);const p:[RegExp,number][]=[[/\b(ipo|initial public offering|public debut|stock listing|prospectus)\b/,45],[/\b(fed|ecb|rate hike|rate cut|cpi|inflation|payrolls|jobs report)\b/,40],[/\b(hormuz|iran|war|missile|sanctions|conflict)\b/,36],[/\b(brent|wti|crude oil|opec|oil)\b/,30],[/\b(gold|silver|copper)\b/,28],[/\b(usd|eur|jpy|gbp|forex|fx|exchange rate)\b/,27],[/\b(bitcoin|ethereum|crypto|stablecoin|spot etf)\b/,25],[/\b(earnings|guidance|revenue|profit|merger|acquisition)\b/,24]];for(const [r,v] of p)if(r.test(x))n+=v;n+=TRUSTED[source]??0;if(BAD.test(x))n-=70;return n}
function imp(cat:string,sc:number,t:string){const x=t.toLowerCase();if(sc>=112)return"critical";if(cat==="ipo"&&/\b(priced|price range|oversubscribed|debut|listing|raises|raised|valuation|billion|million)\b/.test(x))return"important";if(/\b(fed|ecb|rate hike|rate cut|cpi|inflation|payrolls|jobs report|hormuz|iran|war|opec|brent|wti|oil.*100|100.*oil)\b/.test(x))return"critical";return cat!=="jine"?"important":"normal"}
function impactWhy(cat:string,t:string){const x=t.toLowerCase();if(/\b(rate hike|rate cut|fed|ecb)\b/.test(x))return "Změna očekávání sazeb → výnosy dluhopisů → diskontní sazby → valuace akcií; zároveň může výrazně pohnout kurzem USD a zlatem.";if(/\b(cpi|inflation|pce)\b/.test(x))return "Inflace mění očekávání sazeb a reálných výnosů → přes dluhopisy se dopad přelévá do akcií, USD a zlata.";if(/\b(payrolls|jobs report|employment)\b/.test(x))return "Data o trhu práce mění výhled růstu a sazeb → výnosy dluhopisů → akcie a měny.";if(/\b(hormuz|iran|sanctions|shipping|war|missile)\b/.test(x))return "Geopolitika může zvýšit rizikovou prémii a náklady dopravy/energie → ropa → inflace → sazby → akcie a FX.";if(cat==="ropa")return "Ropa se promítá do nákladů a inflace → mění očekávání sazeb a marže firem; producentům a dovozcům může měnit ziskovost.";if(cat==="ipo")return "Nová emise mění nabídku kapitálu a valuace → ovlivňuje sentiment v sektoru a srovnatelné veřejně obchodované firmy.";if(/\b(earnings|guidance|revenue|profit|merger|acquisition)\b/.test(x))return "Firemní výsledky nebo výhled mění očekávání budoucích zisků → odhady EPS a valuace → konkrétní akcie, sektor i indexy.";if(cat==="krypto")return "ETF toky, regulace nebo likvidita mění očekávaný příliv kapitálu a rizikový apetit → volatilita kryptotrhu.";if(cat==="forex")return "Rozdíl sazeb a očekávání centrálních bank → výnosy dluhopisů → kurz měny a přes něj dovozní inflace.";return WHY[cat]||"Událost může změnit očekávání investorů a přelít se do cen aktiv, volatility a rizikové prémie."}
async function translate(t:string){const c=title(t);try{const r=await fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=cs&hl=cs&dt=t&dj=1&q=${encodeURIComponent(c.slice(0,900))}`,{headers:{"User-Agent":"TradingAcademyCZ/23.0","Accept":"application/json"}});if(!r.ok)return c;const j=await r.json();const out=title((j?.sentences??[]).map((x:any)=>x.trans||"").join(""));return out||c}catch{return c}}
async function translateBatched(rows:any[]){const out:any[]=[];for(let i=0;i<rows.length;i+=4){out.push(...await Promise.all(rows.slice(i,i+4).map(async r=>({...r,title:await translate(r.title)}))));}return out}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:{...cors,"Content-Type":"application/json"}});const url=Deno.env.get("SUPABASE_URL");let key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!key){try{const m=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");key=m.default||Object.values(m)[0]||""}catch{}}if(!url||!key)return new Response(JSON.stringify({error:"Supabase server credentials missing"}),{status:500,headers:{...cors,"Content-Type":"application/json"}});const db=createClient(url,key),now=new Date().toISOString();try{
const targeted:string[]=[];for(const f of FEEDS)for(const s of PRIMARY_SOURCES)targeted.push(`${f.q} domain:${s} -sourcelang:chinese -sourcelang:russian -sourcelang:arabic`);const primary=await Promise.all(targeted.map(get));const broad=await Promise.all(FEEDS.map(f=>get(`${f.q} -sourcelang:chinese -sourcelang:russian -sourcelang:arabic`)));const byUrl=new Map<string,Candidate>();[...primary.flat(),...broad.flat()].forEach((a:any)=>{const t=title(String(a?.title||"")),u=String(a?.url||""),s=host(u);if(!t||!u||BAD.test(t)||!latin(t)||!(s in TRUSTED))return;const cat=classify(t),f=FEEDS.find(x=>x.cat===cat);if(!f)return;const d=dateOf(a.seendate),c:Candidate={cat,score:score(t,cat,f.weight,s,d),date:d,key:norm(t),source:s,title:t,summary:clean(String(a.snippet||a.description||"")),url:u};const old=byUrl.get(u);if(!old||c.score>old.score)byUrl.set(u,c)});
const events=new Map<string,Candidate>();for(const c of byUrl.values()){if(c.key.length<18)continue;const old=events.get(c.key);if(!old||c.score>old.score)events.set(c.key,c)}const all=[...events.values()].sort((a,b)=>b.score-a.score||b.date.getTime()-a.date.getTime());const quota:Record<string,number>={ipo:4,makro:4,akcie:4,ropa:4,komodity:3,geopolitika:4,forex:3,krypto:4};const chosen:Candidate[]=[];const counts:Record<string,number>={};for(const cat of Object.keys(quota)){const hit=all.find(c=>c.cat===cat);if(hit){chosen.push(hit);counts[cat]=1}}for(const c of all){if(chosen.includes(c))continue;const max=quota[c.cat]??2;if((counts[c.cat]||0)>=max)continue;chosen.push(c);counts[c.cat]=(counts[c.cat]||0)+1;if(chosen.length>=24)break}if(!chosen.length)throw new Error("Nenalezeny vhodné články z ověřených finančních zdrojů.");
const rawRows=chosen.slice(0,24).map((c:any,i)=>{const sc=score(c.title,c.cat,FEEDS.find(f=>f.cat===c.cat)?.weight||7,c.source,c.date);return{title:c.title,slug:`news-${Date.now()}-${i}`,summary:(c.summary||`Událost v kategorii ${c.cat}.`).slice(0,700),why_it_matters:impactWhy(c.cat,c.title),category:c.cat,importance:imp(c.cat,sc,c.title),published_at:c.date.toISOString(),source_name:NAMES[c.source]||c.source,source_url:c.url,tags:[c.cat,"live","trhy",c.source],updated_at:now}});const rows=await translateBatched(rawRows);
await db.from("news_articles").delete().eq("importance","normal");for(const r of rows){const {data:e}=await db.from("news_articles").select("id").eq("source_url",r.source_url).maybeSingle();if(e?.id)await db.from("news_articles").update(r).eq("id",e.id);else await db.from("news_articles").insert(r)}await db.from("news_articles").delete().in("importance",["important","critical"]).lt("published_at",new Date(Date.now()-365*24*60*60*1000).toISOString());await db.from("news_refresh_state").upsert({id:true,last_refreshed_at:now,last_success_at:now,last_error:null,updated_at:now});return new Response(JSON.stringify({ok:true,count:rows.length,refreshed_at:now,categories:counts,sources:[...new Set(rows.map((r:any)=>r.source_name))]}),{headers:{...cors,"Content-Type":"application/json"}})}catch(e){const msg=e instanceof Error?e.message:String(e);await db.from("news_refresh_state").upsert({id:true,last_refreshed_at:now,last_error:msg,updated_at:now});return new Response(JSON.stringify({ok:false,error:msg}),{status:500,headers:{...cors,"Content-Type":"application/json"}})}});