/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstrumentyRouteImport } from './routes/instrumenty'
import { Route as KurzyRouteImport } from './routes/kurzy'
import { Route as LekceSlugRouteImport } from './routes/lekce.$slug'
import { Route as SlovnikRouteImport } from './routes/slovnik'
import { Route as StylyRouteImport } from './routes/styly'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPrehledRouteImport } from './routes/_authenticated/prehled'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const InstrumentyRoute = InstrumentyRouteImport.update({ id: '/instrumenty', path: '/instrumenty', getParentRoute: () => rootRouteImport } as any)
const KurzyRoute = KurzyRouteImport.update({ id: '/kurzy', path: '/kurzy', getParentRoute: () => rootRouteImport } as any)
const LekceSlugRoute = LekceSlugRouteImport.update({ id: '/lekce/$slug', path: '/lekce/$slug', getParentRoute: () => rootRouteImport } as any)
const SlovnikRoute = SlovnikRouteImport.update({ id: '/slovnik', path: '/slovnik', getParentRoute: () => rootRouteImport } as any)
const StylyRoute = StylyRouteImport.update({ id: '/styly', path: '/styly', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedPrehledRoute = AuthenticatedPrehledRouteImport.update({ id: '/prehled', path: '/prehled', getParentRoute: () => AuthenticatedRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instrumenty': typeof InstrumentyRoute
  '/kurzy': typeof KurzyRoute
  '/lekce/$slug': typeof LekceSlugRoute
  '/slovnik': typeof SlovnikRoute
  '/styly': typeof StylyRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/prehled': typeof AuthenticatedPrehledRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instrumenty': typeof InstrumentyRoute
  '/kurzy': typeof KurzyRoute
  '/lekce/$slug': typeof LekceSlugRoute
  '/slovnik': typeof SlovnikRoute
  '/styly': typeof StylyRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/prehled': typeof AuthenticatedPrehledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instrumenty': typeof InstrumentyRoute
  '/kurzy': typeof KurzyRoute
  '/lekce/$slug': typeof LekceSlugRoute
  '/slovnik': typeof SlovnikRoute
  '/styly': typeof StylyRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/prehled': typeof AuthenticatedPrehledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/instrumenty' | '/kurzy' | '/lekce/$slug' | '/slovnik' | '/styly' | '/auth' | '/reset-password' | '/admin' | '/prehled'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/instrumenty' | '/kurzy' | '/lekce/$slug' | '/slovnik' | '/styly' | '/auth' | '/reset-password' | '/admin' | '/prehled'
  id: '__root__' | '/' | '/instrumenty' | '/kurzy' | '/lekce/$slug' | '/slovnik' | '/styly' | '/auth' | '/reset-password' | '/_authenticated' | '/admin' | '/prehled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstrumentyRoute: typeof InstrumentyRoute
  KurzyRoute: typeof KurzyRoute
  LekceSlugRoute: typeof LekceSlugRoute
  SlovnikRoute: typeof SlovnikRoute
  StylyRoute: typeof StylyRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
}
export interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPrehledRoute: typeof AuthenticatedPrehledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/instrumenty': { id: '/instrumenty'; path: '/instrumenty'; fullPath: '/instrumenty'; preLoaderRoute: typeof InstrumentyRouteImport; parentRoute: typeof rootRouteImport }
    '/kurzy': { id: '/kurzy'; path: '/kurzy'; fullPath: '/kurzy'; preLoaderRoute: typeof KurzyRouteImport; parentRoute: typeof rootRouteImport }
    '/lekce/$slug': { id: '/lekce/$slug'; path: '/lekce/$slug'; fullPath: '/lekce/$slug'; preLoaderRoute: typeof LekceSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/slovnik': { id: '/slovnik'; path: '/slovnik'; fullPath: '/slovnik'; preLoaderRoute: typeof SlovnikRouteImport; parentRoute: typeof rootRouteImport }
    '/styly': { id: '/styly'; path: '/styly'; fullPath: '/styly'; preLoaderRoute: typeof StylyRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/admin': { id: '/_authenticated/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AuthenticatedAdminRouteImport; parentRoute: typeof AuthenticatedRouteImport }
    '/_authenticated/prehled': { id: '/_authenticated/prehled'; path: '/prehled'; fullPath: '/prehled'; preLoaderRoute: typeof AuthenticatedPrehledRouteImport; parentRoute: typeof AuthenticatedRouteImport }
  }
}

const authenticatedRouteChildren: AuthenticatedRouteChildren = { AuthenticatedAdminRoute, AuthenticatedPrehledRoute }
AuthenticatedRoute._addFileChildren(authenticatedRouteChildren)
const rootRouteChildren: RootRouteChildren = { IndexRoute, InstrumentyRoute, KurzyRoute, LekceSlugRoute, SlovnikRoute, StylyRoute, AuthRoute, ResetPasswordRoute, AuthenticatedRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> }
}
